jobs:
  ruby:
    name: noticekung
    runs-on: ubuntu-latest
    steps:
      - uses: zhulik/redis-action@v1.0.0
        with:
          redis version: "4"

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "5.7.17"
          mysql root password: "0614015420"

      - uses: actions/checkout@v1.0.0

      - name: Setup Ruby
        uses: actions/setup-ruby@v1.0.0
        with:
          ruby-version: 2.5.5

      - name: Install Dependencies
        run: bundle install

      - name: Setup Database
        env:
          RAILS_ENV: setup
          DATABASE_URL: mysql2://root:test@127.0.0.1/test
        run: bundle exec rake db:create db:schema:load --trace

      - name: Run 
        env:
          RAILS_ENV: run
          DATABASE_URL: mysql2://root:test@127.0.0.1/test
        run: bundle exec rspec
